### ISSUE TITLE
build之后一打开就闪退

### ISSUE THREAD

**Issue by chenyusheng** [yxs666/cniao5-news#1]
FATAL EXCEPTION: main
                                                                        Process: com.cniao5.app36kr_cnk, PID: 11836
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;
                                                                            at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1185)
                                                                            at android.support.design.widget.TabLayout.createTabView(TabLayout.java:656)
                                                                            at android.support.design.widget.TabLayout.addTabView(TabLayout.java:695)
                                                                            at android.support.design.widget.TabLayout.addTab(TabLayout.java:386)
                                                                            at android.support.design.widget.TabLayout.addTab(TabLayout.java:361)
                                                                            at android.support.design.widget.TabLayout.setTabsFromPagerAdapter(TabLayout.java:645)
                                                                            at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:616)
                                                                            at com.cniao5.app36kr_cnk.fragment.MainInfoFragment.initValidata(MainInfoFragment.java:72)
                                                                            at com.cniao5.app36kr_cnk.fragment.MainInfoFragment.onCreateView(MainInfoFragment.java:42)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
                                                                            at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
                                                                            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
                                                                            at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                            at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
                                                                            at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
                                                                            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:779)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:729)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:823)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:823)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:823)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:823)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                            at android.app.Activity.setContentView(Activity.java:2191)
                                                                            at com.cniao5.app36kr_cnk.ui.MainActivity.onCreate(MainActivity.java:46)
                                                                            at android.app.Activity.performCreate(Activity.java:6323)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
                                                                            at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5544)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.TintManager" on path: DexPathList[[zip file "/data/app/com.cniao5.app36kr_cnk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cniao5.app36kr_cnk-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        	at java.lang.ClassLoader.loadCl

**Comment by xinyangcuncun** [comment]
这个得改造一下buid 的引用，把原项目统一换成改成23.3.0

**Comment by lh414035210** [comment]
Error:failed to find Build Tools revision 23.3.0
<a href="install.build.tools">Install Build Tools 23.3.0 and sync project</a>  
按照你说的错,出了这样的错误..

**Comment by plmmmmlq** [comment]
1、Project Structure
- Gradle version -> 2.14.1
- Android Plugin Version ->2.2.2

 2、cwidgetutil -> build.gradle
``
compile 'com.android.support:appcompat-v7:23.1.1'
``

**Comment by CoderNixx** [comment]
这个问题解决了吗？我也是这个问题，compile 'com.android.support:appcompat-v7:23.1.1'把这个改了之后又出现新的问题了
FATAL EXCEPTION: main
Process: com.cniao5.app36kr_cnk, PID: 5179
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference
at com.cniao5.app36kr_cnk.biz.HeadDataManager.getHeadBeans(HeadDataManager.java:31)
at com.cniao5.app36kr_cnk.fragment.HomeFragment$1.requestSuccess(HomeFragment.java:128)
at com.cniao5.app36kr_cnk.utils.OkhttpManager$5.run(OkhttpManager.java:222)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5507)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by QuincySx** [comment]
哎，你们都没有查报错原因吗，大概是36kr做了反爬虫，里面的内容都是用 script 渲染的，jsoup 爬不到了,报个 Null 很正常

**Comment by zhaolin2020** [comment]
性能卡顿问题！
public void draw(Canvas canvas) {  
	Bitmap bitmap = Bitmap.createBitmap(getWidth(), getHeight(), Config.ARGB_8888);  
        ............
}

**Comment by lavaguezf** [comment]
好像是Jsoup爬不到了，请问怎么解决呢

**Comment by yuku123** [comment]
Jsoup爬不到数据，返回null

**Comment by peng093** [comment]
1.先解决点击启动页闪退的问题
compile 'com.android.support:design:23.3.0'
compile 'com.android.support:appcompat-v7:23.3.0'
2.进入首页闪退的问题
找到HeadDataManager类，在getHeadBeans方法加入一个为空判断

```
/**
	 * 进行根据地址抓取顶部广告数据
	 * @param pUrl
	 * @return
	 */
	public List<AdHeadBean> getHeadBeans(Document document){
	   List<AdHeadBean> adHeadBeans=new ArrayList<AdHeadBean>();
	   Elements elements=document.select("div.head-images");
	   if (elements==null || elements.size()==0){
	   	return null;
	   }
	   Elements links = elements.first().select("a[data-lazyload]"); //带有data-lazyload属性的a元素
		if(links==null){
			return null;
		}
		for (Element element : links) {
			String title=element.text();
			String href=element.attr("href");
			String imgurl= ImageUtils.getCutImageUrl(element.attr("data-lazyload"));
			String mask= element.select("span").first().text();
			AdHeadBean bean=new AdHeadBean();
			bean.setTitle(title);
			bean.setImgurl(imgurl);
			bean.setHref(href);
			bean.setMask(mask);
			adHeadBeans.add(bean);
		}
       return adHeadBeans;
	}
```
